#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Caldroid.Xamarin.Resource", IsApplication=false)]

namespace Caldroid.Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public static int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f010014
			public static int state_date_disabled = 2130771988;
			
			// aapt resource value: 0x7f010015
			public static int state_date_prev_next_month = 2130771989;
			
			// aapt resource value: 0x7f010013
			public static int state_date_selected = 2130771987;
			
			// aapt resource value: 0x7f010012
			public static int state_date_today = 2130771986;
			
			// aapt resource value: 0x7f010010
			public static int styleCaldroidGridView = 2130771984;
			
			// aapt resource value: 0x7f01000a
			public static int styleCaldroidHeader = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int styleCaldroidLeftArrow = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public static int styleCaldroidMonthName = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int styleCaldroidNormalCell = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public static int styleCaldroidRightArrow = 2130771980;
			
			// aapt resource value: 0x7f01000f
			public static int styleCaldroidSquareCell = 2130771983;
			
			// aapt resource value: 0x7f010009
			public static int styleCaldroidViewLayout = 2130771977;
			
			// aapt resource value: 0x7f010011
			public static int styleCaldroidWeekdayView = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public static int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050011
			public static int caldroid_333 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public static int caldroid_555 = 2131034130;
			
			// aapt resource value: 0x7f050008
			public static int caldroid_black = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public static int caldroid_darker_gray = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public static int caldroid_gray = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public static int caldroid_holo_blue_dark = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public static int caldroid_holo_blue_light = 2131034126;
			
			// aapt resource value: 0x7f050013
			public static int caldroid_light_red = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public static int caldroid_lighter_gray = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public static int caldroid_middle_gray = 2131034125;
			
			// aapt resource value: 0x7f050010
			public static int caldroid_sky_blue = 2131034128;
			
			// aapt resource value: 0x7f050009
			public static int caldroid_transparent = 2131034121;
			
			// aapt resource value: 0x7f050007
			public static int caldroid_white = 2131034119;
			
			// aapt resource value: 0x7f050014
			public static int cell_text_color = 2131034132;
			
			// aapt resource value: 0x7f050015
			public static int cell_text_color_dark = 2131034133;
			
			// aapt resource value: 0x7f050003
			public static int notification_action_color_filter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int notification_icon_bg_color = 2131034116;
			
			// aapt resource value: 0x7f050000
			public static int notification_material_background_media_default_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int primary_text_default_material_dark = 2131034113;
			
			// aapt resource value: 0x7f050005
			public static int ripple_material_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public static int secondary_text_default_material_dark = 2131034114;
			
			// aapt resource value: 0x7f050006
			public static int secondary_text_default_material_light = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public static int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public static int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public static int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public static int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public static int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public static int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public static int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public static int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public static int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public static int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public static int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public static int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public static int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public static int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public static int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public static int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public static int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public static int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public static int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public static int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int calendar_next_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int calendar_prev_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int cell_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int cell_bg_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int disable_cell = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int disabled_cell_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int left_arrow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int notification_action_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int notification_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int notification_bg_low = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int notification_bg_low_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int notification_bg_low_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int notification_bg_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int notification_bg_normal_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int notification_icon_background = 2130837518;
			
			// aapt resource value: 0x7f020015
			public static int notification_template_icon_bg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int notification_template_icon_low_bg = 2130837526;
			
			// aapt resource value: 0x7f02000f
			public static int notification_tile_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int notify_panel_notification_icon_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int red_border = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int red_border_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int red_border_gray_bg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int right_arrow = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0016
			public static int action0 = 2131361814;
			
			// aapt resource value: 0x7f0a0013
			public static int action_container = 2131361811;
			
			// aapt resource value: 0x7f0a001a
			public static int action_divider = 2131361818;
			
			// aapt resource value: 0x7f0a0014
			public static int action_image = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public static int action_text = 2131361813;
			
			// aapt resource value: 0x7f0a0024
			public static int actions = 2131361828;
			
			// aapt resource value: 0x7f0a0006
			public static int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public static int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a0011
			public static int calendar_gridview = 2131361809;
			
			// aapt resource value: 0x7f0a000c
			public static int calendar_left_arrow = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public static int calendar_month_year_textview = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public static int calendar_right_arrow = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public static int calendar_title_view = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public static int calendar_tv = 2131361810;
			
			// aapt resource value: 0x7f0a0017
			public static int cancel_action = 2131361815;
			
			// aapt resource value: 0x7f0a001f
			public static int chronometer = 2131361823;
			
			// aapt resource value: 0x7f0a0026
			public static int end_padder = 2131361830;
			
			// aapt resource value: 0x7f0a0008
			public static int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0021
			public static int icon = 2131361825;
			
			// aapt resource value: 0x7f0a0025
			public static int icon_group = 2131361829;
			
			// aapt resource value: 0x7f0a0020
			public static int info = 2131361824;
			
			// aapt resource value: 0x7f0a0009
			public static int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public static int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public static int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0019
			public static int media_actions = 2131361817;
			
			// aapt resource value: 0x7f0a0010
			public static int months_infinite_pager = 2131361808;
			
			// aapt resource value: 0x7f0a000a
			public static int normal = 2131361802;
			
			// aapt resource value: 0x7f0a0023
			public static int notification_background = 2131361827;
			
			// aapt resource value: 0x7f0a001c
			public static int notification_main_column = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public static int notification_main_column_container = 2131361819;
			
			// aapt resource value: 0x7f0a0022
			public static int right_icon = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public static int right_side = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public static int status_bar_latest_event_content = 2131361816;
			
			// aapt resource value: 0x7f0a0002
			public static int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public static int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public static int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a001e
			public static int time = 2131361822;
			
			// aapt resource value: 0x7f0a0005
			public static int title = 2131361797;
			
			// aapt resource value: 0x7f0a000f
			public static int weekday_gridview = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public static int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int status_bar_notification_info_maxnum = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int calendar_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int date_grid_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int normal_date_cell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int notification_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int notification_action_tombstone = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int notification_media_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int notification_media_cancel_action = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int notification_template_big_media = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int notification_template_big_media_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int notification_template_big_media_narrow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int notification_template_big_media_narrow_custom = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int notification_template_custom_big = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int notification_template_icon_group = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int notification_template_lines_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int notification_template_media = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int notification_template_media_custom = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int notification_template_part_chronometer = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int notification_template_part_time = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int square_date_cell = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int weekday_textview = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public static int library_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int status_bar_notification_info_overflow = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f04001f
			public static int AppBaseTheme = 2130968607;
			
			// aapt resource value: 0x7f04000c
			public static int CaldroidDefault = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public static int CaldroidDefaultArrowButton = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public static int CaldroidDefaultCalendarHeader = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public static int CaldroidDefaultCalendarViewLayout = 2130968589;
			
			// aapt resource value: 0x7f040015
			public static int CaldroidDefaultCell = 2130968597;
			
			// aapt resource value: 0x7f040018
			public static int CaldroidDefaultDark = 2130968600;
			
			// aapt resource value: 0x7f040019
			public static int CaldroidDefaultDarkCalendarViewLayout = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public static int CaldroidDefaultDarkCell = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public static int CaldroidDefaultDarkGridView = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public static int CaldroidDefaultDarkMonthName = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public static int CaldroidDefaultDarkNormalCell = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public static int CaldroidDefaultDarkSquareCell = 2130968606;
			
			// aapt resource value: 0x7f040014
			public static int CaldroidDefaultGridView = 2130968596;
			
			// aapt resource value: 0x7f040010
			public static int CaldroidDefaultLeftButton = 2130968592;
			
			// aapt resource value: 0x7f040012
			public static int CaldroidDefaultMonthName = 2130968594;
			
			// aapt resource value: 0x7f040016
			public static int CaldroidDefaultNormalCell = 2130968598;
			
			// aapt resource value: 0x7f040011
			public static int CaldroidDefaultRightButton = 2130968593;
			
			// aapt resource value: 0x7f040017
			public static int CaldroidDefaultSquareCell = 2130968599;
			
			// aapt resource value: 0x7f040013
			public static int CaldroidDefaultWeekday = 2130968595;
			
			// aapt resource value: 0x7f040005
			public static int TextAppearance_Compat_Notification = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int TextAppearance_Compat_Notification_Info = 2130968582;
			
			// aapt resource value: 0x7f040000
			public static int TextAppearance_Compat_Notification_Info_Media = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public static int TextAppearance_Compat_Notification_Line2 = 2130968587;
			
			// aapt resource value: 0x7f040004
			public static int TextAppearance_Compat_Notification_Line2_Media = 2130968580;
			
			// aapt resource value: 0x7f040001
			public static int TextAppearance_Compat_Notification_Media = 2130968577;
			
			// aapt resource value: 0x7f040007
			public static int TextAppearance_Compat_Notification_Time = 2130968583;
			
			// aapt resource value: 0x7f040002
			public static int TextAppearance_Compat_Notification_Time_Media = 2130968578;
			
			// aapt resource value: 0x7f040008
			public static int TextAppearance_Compat_Notification_Title = 2130968584;
			
			// aapt resource value: 0x7f040003
			public static int TextAppearance_Compat_Notification_Title_Media = 2130968579;
			
			// aapt resource value: 0x7f040009
			public static int Widget_Compat_NotificationActionContainer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int Widget_Compat_NotificationActionText = 2130968586;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Cell = new int[] {
					16842904,
					16842964};
			
			// aapt resource value: 1
			public static int Cell_android_background = 1;
			
			// aapt resource value: 0
			public static int Cell_android_textColor = 0;
			
			public static int[] DateState = new int[] {
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 2
			public static int DateState_state_date_disabled = 2;
			
			// aapt resource value: 3
			public static int DateState_state_date_prev_next_month = 3;
			
			// aapt resource value: 1
			public static int DateState_state_date_selected = 1;
			
			// aapt resource value: 0
			public static int DateState_state_date_today = 0;
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public static int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public static int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
